### ISSUE TITLE
Update and improve integration with dry-struct

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#241]
`Types::Struct` has been extracted to `Dry::Struct` in [dry-struct](https://github.com/dry-rb/dry-struct) gem and we gotta update dry-validation to use it. Also, this should be **optional**.
## TODO
- [x] extract struct-related functionality so it can be optionally included
- [ ] include struct-related support conditionally when `Dry::Struct` is present
- [ ] improve the integration so that complex structs with types like array with members or nested structs is also supported
